spring.application.name=demo
#management.endpoints.web.exposure.include=health, info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
#management.endpoints.web.exposure.exclude=health, info

info.app.name = My app
info.app.description = A fun app!
info.app.version = 1.0.0

#Define my properties
coach.name = Mickey
team.name = The Mouse Club

#change Spring Boot embedded server port
server.port = 7070

#set the context path of the application
server.servlet.context-path = /demo