spring.application.name=demo
#management.endpoints.web.exposure.include=health, info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name = My app
info.app.description = A fun app!
info.app.version = 1.0.0